### ISSUE TITLE
example not working Ropsten deprecated

### ISSUE THREAD

**Issue by hcheng826** [tkey/tkey-example#2]
Hi team,
Thanks for the great project! I am trying out the example, but I encounter some errors 
1. initialization: Is there an example about how I can initialize the SDK and metadata?
2. Ropsten RPC url: Is it because of Ropsten getting deprecated, is there a recommended way to fix this?
3. Related to the previous point, I am wondering how tKey is related to the RPC url? My understanding is that all the web3auth process: the shares generation, recovery, encryption, decryption all happen off-chain. The only point it involves the chain is when we reconstruct private key and send out the transaction. Is it not the case? And if I am building on chains other than Ropsten, should I set additional configs?

<img width="477" alt="image" src="https://user-images.githubusercontent.com/23033847/194809928-4eb64bcb-58f1-47b3-adf0-65d79e3dc9e3.png">

Appreciate your help!

**Comment by Deveshb15** [comment]
seems like no one is maintaining this anymore

**Comment by Deveshb15** [comment]
btw this works on polygon mumbai testnet you can change the network url to the polygon testnet and it'll work

**Comment by hcheng826** [comment]
got it. Thanks for the reply! I am not actively working on this anymore. Let me close the issue.
